### PR TITLE
Added extra Graph problems

### PR DESCRIPTION
**Pull request by Krunal-Karena**
Please review my PR.

### CODE REVIEW

**Comment by tarunsinghdev** [comment]
Hi Krunal, great work!
However, the problems you solved are from the `450 DSA` list and do not count as extras. Extra problems are a problem that does not belong to the `450 DSA` list.
Therefore, you can add these problems under the `Graph` folder present at the root, no need to add these under `Extras` folder.
While you are there make sure you update the `Readme.md` table as well.

**Comment by Krunal-Karena** [comment]
your repository is excluded from Hacktoberfest ???

**Comment by tarunsinghdev** [comment]
> your repository is excluded from Hacktoberfest ???

No, I haven't received any intimation regarding this. Is this repo showing excluded to you? If yes, attach a screenshot as proof so that I can rectify the same.

**Comment by Krunal-Karena** [comment]
Screenshot 2022-10-08 114617

**Comment by tarunsinghdev** [comment]
Seems like the repo has been blocked for hacktoberfest as the PRs are not considered high-quality contributions. 

However, I really liked your solutions. Would you spare some time to make the changes I requested? It would be a great help for the people accessing this repo in the future.

I'll merge your PR, once the changes are done. Looking forward to the changes.
Happy Hacking. :)

**Comment by tarunsinghdev** [comment]
Excellent!

**Pull request merged**
