### PR TITLE
37_Maximum Product Subarray.cpp

### PR DESCRIPTION
**Pull request by payal1206**

### CODE REVIEW

**Comment by tarunsinghdev** [comment]
Hey, please update the `readme.md` file for the same.

**Comment by payal1206** [comment]
> Hey, please update the `readme.md` file for the same.

Done

**Comment by tarunsinghdev** [comment]
No need to raise a separate PR, please merge your branch `payal1206:patch-2` to this branch and push the changes.

**Comment by payal1206** [comment]
> No need to raise a separate PR, please merge your branch `payal1206:patch-2` to this branch and push the changes.

ok, done

**Comment by tarunsinghdev** [comment]
Well done!

**Comment by payal1206** [comment]
I am getting this PR excluded why ??? Please tell me
 
image

**Comment by tarunsinghdev** [comment]
Hey, payal! Unfortunately, it seems like the repo has been blocked for hacktoberfest as the PRs are not considered high-quality.

**Pull request merged**
