### PR TITLE
added diagonal_sort_matrix.cpp

### PR DESCRIPTION
**Pull request by awdhesh-kumar27**
added diagonal_sort_matrix.cpp

Please merge the PR with hactorberfest Label.   Looking for first accepted PR with hactoberfest label.

### CODE REVIEW

**Comment by tarunsinghdev** [comment]
Hey, thank you for contributing. Please solve the problems from [this](https://drive.google.com/file/d/1FMdN_OCfOI0iAeDlqswCiC2DZzD4nPsb/view) list.
Also please save your file as QuestionNo_ProblemName.cpp as per this [sheet](https://drive.google.com/file/d/1FMdN_OCfOI0iAeDlqswCiC2DZzD4nPsb/view). And plz update the readme.md file for the same mentioning the time and space complexity.

I'll review and merge the solutions from the [sheet](https://drive.google.com/file/d/1FMdN_OCfOI0iAeDlqswCiC2DZzD4nPsb/view) mentioned.
Thanks.

**Comment by awdhesh-kumar27** [comment]
> Hey, thank you for contributing. Please solve the problems from [this](https://drive.google.com/file/d/1FMdN_OCfOI0iAeDlqswCiC2DZzD4nPsb/view) list. Also please save your file as QuestionNo_ProblemName.cpp as per this [sheet](https://drive.google.com/file/d/1FMdN_OCfOI0iAeDlqswCiC2DZzD4nPsb/view). And plz update the readme.md file for the same mentioning the time and space complexity.
> 
> I'll review and merge the solutions from the [sheet](https://drive.google.com/file/d/1FMdN_OCfOI0iAeDlqswCiC2DZzD4nPsb/view) mentioned. Thanks.

Hey @tarunsinghdev ,
I want to solve for Binary Tree but in Readme.md file there is no Binary Tree Table . So how can we add solution of binary tree problems. 
is only Cross ticked problems allowed for pull request ?

**Comment by tarunsinghdev** [comment]
All the questions from the [sheet](https://drive.google.com/file/d/1FMdN_OCfOI0iAeDlqswCiC2DZzD4nPsb/view) that are not solved already or if you have some efficient solution for the already solved problem are eligible.
For the sections not present in the `Readme.md`, you can simply create a section for eg. Binary Tree, and fill in the table with the correct question number from the sheet with the respective time and space complexities.
So, if you solve the 4th question from the **sheet**  which is 'Diameter of a tree', your filename should be `4_DiameterOfTheTree.cpp`.
Hope this helps.

**Comment by awdhesh-kumar27** [comment]
> All the questions from the [sheet](https://drive.google.com/file/d/1FMdN_OCfOI0iAeDlqswCiC2DZzD4nPsb/view) that are not solved already or if you have some efficient solution for the already solved problem are eligible. For the sections not present in the `Readme.md`, you can simply create a section for eg. Binary Tree, and fill in the table with the correct question number from the sheet with the respective time and space complexities. So, if you solve the 4th question from the **sheet** which is 'Diameter of a tree', your filename should be `4_DiameterOfTheTree.cpp`. Hope this helps.

I updated the readme.md file and as well as added the code please check ASAP.

**Pull request closed without merging**
