### PR TITLE
12_BottomViewOfBinaryTree.cpp

### PR DESCRIPTION
**Pull request by shivesh41kr**
Love Babbar Sheet - Problem - Bottom View of Binary Tree

### CODE REVIEW

**Comment by tarunsinghdev** [comment]
Hey, great work! Please rename your file in the format `QuestionNo_ProblemName.cpp`. For your case it would be `12_BottomViewOfBinaryTree.cpp`.

Also, avoid making multiple PRs. Please merge your `shivesh41kr:patch-2` branch to this branch. No separate PR is required for updating the `REAME.md` file.

**Comment by tarunsinghdev** [comment]
Hey, please rename your file to `12_BottomViewOfBinaryTree.cpp`.

**Comment by shivesh41kr** [comment]
@tarunsinghdev  check now

**Comment by tarunsinghdev** [comment]
Hey Shivesh, I am talking about your filename and not the PR heading. Your file exists in the `Binary Tree` folder you created, please update the filename and push the changes.

**Comment by shivesh41kr** [comment]
@tarunsinghdev done

**Pull request merged**
