### PR TITLE
Added solution to 4. Find the middle element of a stack

### PR DESCRIPTION
**Pull request by anurrags**

### CODE REVIEW

**Comment by tarunsinghdev** [comment]
Hey, great work! A quick suggestion, please indent your code well for better readability. Also please update the `readme.md` file for the same.

**NOTE:
We have another PR for the same question, the first to create a valid PR with no error will get merged, the other would be marked as duplicate and PR will be closed.**

**Comment by anurrags** [comment]
@tarunsinghdev hey, i have indented the code and edited the readme.md file, please check it and comment if any further changes are required.

**Comment by tarunsinghdev** [comment]
> @tarunsinghdev hey, i have indented the code and edited the readme.md file, please check it and comment if any further changes are required.

Well done! All looks good, merging. Cheers!

**Comment by anurrags** [comment]
@tarunsinghdev as mentioned in hacktoberfest website, the label for merged PR should be "hacktoberfest-accepted". So can you please change the label to exact letters.

**Comment by tarunsinghdev** [comment]
> @tarunsinghdev as mentioned in hacktoberfest website, the label for merged PR should be "hacktoberfest-accepted". So can you please change the label to exact letters.

done.

**Pull request merged**
