### PR TITLE
Create Sieve_of_eratosthenes.cpp

### PR DESCRIPTION
**Pull request by navdiya-nikunj**
- Sieve_of_eratosthenes method
       - Given a number n, print all primes smaller than or equal to n. It is also given that n is a small number.

### CODE REVIEW

**Comment by navdiya-nikunj** [comment]
@tarunsinghdev check my work and let me know if any changes needed. and can you please label it hactoberfest-accepted.

**Comment by tarunsinghdev** [comment]
Hi, this problem does not belong to the `450 DSA sheet` and therefore needs to be added under `Extras` > `Arrays` > `Sieve_of_eratosthenes.cpp`.

For more details, please look at this [issue](https://github.com/tarunsinghdev/DSA-CRACKER/issues/24#issuecomment-1272236331).

**Comment by navdiya-nikunj** [comment]
Done @tarunsinghdev check it

**Comment by tarunsinghdev** [comment]
Hey @navdiya-nikunj , you pushed an empty file please check.

**Pull request closed without merging**
